name: Gazebo RViz CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        gz: ['garden']
        ros: ['rolling']
    container:
      image: osrf/ros:${{ matrix.ros }}-desktop
    env:
      GZ_VERSION: ${{ matrix.gz }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        apt update -y
        apt install -y wget
        sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
        wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
        apt update -y
        apt install -y libgz-common5-dev \
                       libgz-math7-dev \
                       libgz-rendering7-dev \
                       libgz-gui7-dev

    - name: Setup colcon workspace
      id: configure
      run: |
        cd ..
        mkdir -p /home/colcon_ws/src
        cp -r gz-rviz /home/colcon_ws/src/
    - name: Build project
      id: build
      run: |
        cd /home/colcon_ws/
        . /opt/ros/${{ matrix.ros }}/setup.sh
        colcon build
    - name: Run tests
      id: test
      run: |
        cd /home/colcon_ws/
        . /opt/ros/${{ matrix.ros }}/setup.sh
        colcon test --event-handlers console_direct+
        colcon test-result
